services:
  # ========== LOCAL REDIS INSTANCE ==========
  redis:
    container_name: redis
    build: ./redis
    ports:
      - '6379:6379'

  # ========== REDIS INSIGHT UI ==========
  redis-insight:
    container_name: redis-insight
    build: ./redis-insight
    ports:
      - '8100:5540'
    depends_on:
      - redis
    environment:
      - RI_REDIS_HOST=redis
      - RI_REDIS_PORT=6379

  # ========== LOCAL MONGODB INSTANCE ==========
  mongodb:
    container_name: mongodb
    build: ./mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  # ========== MONGODB EXPRESS UI ==========
  mongodb-express:
    container_name: mongodb-express
    build: ./mongo-express
    ports:
      - '8200:8081'
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@mongodb:27017
      - ME_CONFIG_BASICAUTH=false
